version: 2
jobs:
  build:
    docker:
      - image: edasque/qmk_firmware
    steps:
      - checkout
      - run:
          name: docker build
          command: docker run -e keyboard=ergodox_ez -e keymap=castella --rm -v $('pwd'):/qmk:rw edasque/qmk_firmware
      - store_artifacts:
          path: .build/ergodox_ez_castella.hex
