version: 2
jobs:
  build:
    docker:
      - image: edasque/qmk_firmware
    steps:
      - checkout
      - run:
          name: docker build
          command: make clean; make keyboard=ergodox_ez keymap=castella
      - store_artifacts:
          path: .build/ergodox_ez_castella.hex
